# Generated by Django 5.2 on 2025-05-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post', 'user')},
        ),
        migrations.RemoveField(
            model_name='likes',
            name='num_likes',
        ),
    ]
