# Generated by Django 5.2 on 2025-05-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
