# Generated by Django 5.2 on 2025-05-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ressources'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressources',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
