# Generated by Django 5.2 on 2025-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_token_user_id_token_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
