# Generated by Django 5.2 on 2025-05-16 22:51

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_token_user_token_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[api.models.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='groups/')),
                ('bio', models.CharField(max_length=500, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered_groups', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(null=True, related_name='member_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
