# Generated by Django 5.2 on 2025-05-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groupe'),
        ),
    ]
