# Generated by Django 5.2 on 2025-05-24 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_groupmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='users',
            field=models.ManyToManyField(related_name='member_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(choices=[('false_news', 'Désinformation ou fausses nouvelles'), ('spam', 'Spam ou arnaques'), ('identity_theft', "Usurpation d'identité ou faux comptes")], default='false_news', max_length=255)),
                ('post_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.posts')),
                ('user_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
