# Generated by Django 5.2 on 2025-05-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_groupe_users_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='sender',
        ),
        migrations.AlterField(
            model_name='reports',
            name='cause',
            field=models.CharField(choices=[('false_news', 'Désinformation ou fausses nouvelles'), ('spam', 'Spam ou arnaques'), ('identity_theft', "Usurpation d'identité ou faux comptes"), ('inappropriate_content', 'Contenu inapproprié'), ('other', 'Autre')], default='false_news', max_length=255),
        ),
        migrations.DeleteModel(
            name='GroupeConversation',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
